{{/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.crds }}
{{- if not (.Capabilities.APIVersions.Has "metacontroller.k8s.io/v1alpha1") }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: compositecontrollers.metacontroller.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
spec:
  group: metacontroller.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                generateSelector:
                  type: boolean
                parentResource:
                  type: object
                  properties:
                    apiVersion:
                      type: string
                    resource:
                      type: string
                childResources:
                  type: array
                  items:
                    type: object
                    properties:
                      apiVersion:
                        type: string
                      resource:
                        type: string
                hooks:
                  type: object
                  properties:
                    sync:
                      type: object
                      properties:
                        webhook:
                          type: object
                          properties:
                            url:
                              type: string
  scope: Cluster
  names:
    plural: compositecontrollers
    singular: compositecontroller
    kind: CompositeController
    shortNames:
    - cc
    - cctl
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: decoratorcontrollers.metacontroller.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
spec:
  group: metacontroller.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
  scope: Cluster
  names:
    plural: decoratorcontrollers
    singular: decoratorcontroller
    kind: DecoratorController
    shortNames:
    - dec
    - decorators
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: controllerrevisions.metacontroller.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
spec:
  group: metacontroller.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
  scope: Namespaced
  names:
    plural: controllerrevisions
    singular: controllerrevision
    kind: ControllerRevision
{{- end }}
{{- end }}
